### ISSUE TITLE
Can't install from pip (PyPi)

### ISSUE THREAD

**Issue by lynnpepin** [rentruewang/aioway#11]
I am unable to install this from PyPi using Pip. I'm not sure why, but I opened this issue in case anyone else was having this problem and was searching here.

The output I get is this:

    pip install koila
    ERROR: Could not find a version that satisfies the requirement koila
    ERROR: No matching distribution found for koila

**Comment by lynnpepin** [comment]
It seems one can install it from GitHub using Pip:

    pip install "git+https://github.com/rentruewang/koila"

(One can also clone and `git install .` which is something that I didn't know. I think this shortcuts that. I don't know if there is any drawback.)

I'll close with comment rather than delete in case anyone else is in the same boat.

**Comment by rentruewang** [comment]
Wait, what?

**Comment by tengfeixue-victor** [comment]
I met the same problem, and pip install "git+https://github.com/rentruewang/koila" does not work.
