### ISSUE TITLE
[BUG] pip can't find the package on Kaggle & Colab

### ISSUE THREAD

**Issue by lukeleeai** [rentruewang/aioway#21]
Hello, as who's suffering from "cuda out of memory" errors on Kaggle notebook, I can't wait to use your package. However, I run into errors when I try to install koila on both Kaggle and Colab notebooks. 

**Describe the bug**
`!pip install koila` outputs the following error message: `ERROR: Could not find a version that satisfies the requirement koila (from versions: none)
ERROR: No matching distribution found for koila` on Kaggle and Colab notebooks.

**To Reproduce**
1. Run `!pip install koila` on Kaggle / Colab

I'd appreciate it if anyone provides me with an alternate solution until this error gets fixed.

**Comment by lukeleeai** [comment]
It seems I can't use it on Kaggle / Colab anyway for now since it uses Python 3.7, which is incompatible with the current version of Koila. Hope it supports a variety of Python versions soon!

**Comment by rentruewang** [comment]
Hi, thanks for your bug report!

I believe that the error you get is precisely because this library doesn't support `3.7` yet. Sorry for causing the confusion!

I'll be closing this issue in favor of #7 .
