### ISSUE TITLE
Can not get is_cuda attribute from LazyTensor

### ISSUE THREAD

**Issue by diggerdu** [rentruewang/aioway#5]

**Comment by rentruewang** [comment]
Noted. Will add this in the near future!

**Comment by rentruewang** [comment]
I'm going to close this in favor of #6. While both this and #6 are caused by the same issue and this came first, I forgot about that and answered why those `property`es cannot be supported in the current implementation [here](https://github.com/rentruewang/koila/issues/6#issuecomment-982746636).
