### ISSUE TITLE
Hi! We are building LazyTensor too!

### ISSUE THREAD

**Issue by Krovatkin** [rentruewang/aioway#8]
Hi! I'm with Pytorch team and it looks like we are also building something similar to koila here: https://github.com/pytorch/pytorch/tree/lazy_tensor_staging . We would love to connect and learn more about your work! 
If you are interested, could you please reply to this issue and drop me a line at k o r o v a i k o n __AT__ gmail.com (no spaces obviously)

**Comment by rentruewang** [comment]
Hi, thanks for reaching out! I would love to share anything I know about this work! It would be awesome if your team implements lazy tensors directly in your library.

I saw shape inference in your source code. As I didn't have time to read over all the source code, I'm wondering, do our `LazyTensor`s work the same way (by storing unevaluated functions or evaluated data)?
